name: english_companion
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.4
  mockito: ^5.4.6
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  wakelock_plus: ^1.3.2
  provider: ^6.1.2
  flutter_tts: ^4.2.2
  path_provider: ^2.1.5
  record: ^6.0.0
  permission_handler: ^12.0.0
  flutter_sound: ^9.28.0
  flutter_secure_storage: ^9.2.4
  multicast_dns: ^0.3.3
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900